### ISSUE TITLE
[Feature/6] 1번 페이지 메인페이지 조회

### ISSUE THREAD

**Issue by bell-person-ii** [yongiCorp/Server#6]
## Description
기능 목록 기준: 1_유저 메인페이지 조회 구현
피그마 기준: 페이지 1-a 에 필요한 API 구현

! 중요
AccessToken 구현 전까진 RequestParam을 통해 URL로 userId를 임시로 받아 기능 구현 예정
-> 이후 AccessToken이 구현되면 Authenticate 객체에서 userId를 추출하여 유저 아이디에 따른 결과를 출력하도록
보안 기능을 적용할 예정

## Checklist
- [ ] AccessToken에서 유저 아이디 추출해서 유저 브랜드 리스트 조회
- [x] AWS S3 이미지 URL 정상 생성 여부 확인하기 
- [ ]  안드로이드에서 AWS S3 이미지 URL을 통해 이미지에 정상 액세스가 가능한지 여부 확인해주기

## PR 유형

- [x] 새로운 기능 추가
- [ ] 버그 수정
- [ ] 코드 리팩토링
- [ ] 문서 수정
- [ ] CI/CD

**Comment by bell-person-ii** [comment]
S3: 미연동, 사진데이터: String 대체, 유저 데이터 & 브랜드 데이터 == 더미데이터 상태에서 Response 정상 구현 확인
주석 삽입 및 N+1 문제 체킹 후 PR 예
![메인페이지 정상 구동확인](https://github.com/yongiCorp/Server/assets/76873740/1ad37fd5-265d-49b7-9881-91e09d8d9dfe)

**Comment by seungheon123** [comment]
brandList 보여줄 때 brand4, brand3 이게 브랜드Id인 거야?

**Comment by bell-person-ii** [comment]
> brandList 보여줄 때 brand4, brand3 이게 브랜드Id인 거야?

프론트에서 파싱할때 기준 잡을수 있게 내가 DTO에서만 뿌려주는 key값이야 메인페이지에서 브랜드 리스트에 내가 주는 데이터는 1. 브랜드 네임, 2. 브랜드 프로필 이미지 URL 두 가지 주려고 ( 0부터 4까지 가야하는데 4부터 0까지 가네... 요건 수정해서 pr 날릴께)

**Comment by bell-person-ii** [comment]
> brandList 보여줄 때 brand4, brand3 이게 브랜드Id인 거야?


전체는 이렇게 생김 


{
    "isSuccess": true,
    "code": "COMMON200",
    "message": "성공입니다",
    "data": {
        "mainBanners": {
            "main-banner0": "brandol p",
            "main-banner1": "p5",
            "main-banner2": "p4",
            "main-banner3": "p3",
            "main-banner4": "p2"
        },
        "subBanners": {
            "sub-banner0": "event file5",
            "sub-banner1": "event file4",
            "sub-banner2": "event file3",
            "sub-banner3": "event file2",
            "sub-banner4": "event file1"
        },
        "brandList": {
            "brand4": {
                "brand-name": "brandol",
                "brand-image": "brandol p"
            },
            "brand3": {
                "brand-name": "brand4 name",
                "brand-image": "p4"
            },
            "brand2": {
                "brand-name": "brand3 name",
                "brand-image": "p3"
            },
            "brand1": {
                "brand-name": "brand2 name",
                "brand-image": "p2"
            },
            "brand0": {
                "brand-name": "brand1 name",
                "brand-image": "p1"
            }
        }
    }
}

**Comment by seungheon123** [comment]
우리가 브랜드 메인페이지 조회를 브랜드id로 하니까 id도 같이 해서 주면 좋을거 같아

**Comment by bell-person-ii** [comment]
> 우리가 브랜드 메인페이지 조회를 브랜드id로 하니까 id도 같이 해서 주면 좋을거 같아

ㅇㅋ 브랜드 id 필드 추가 할께
이미지 파일들을 어떻게 줘야할지가 애매하네.... 그냥 URL 만 줘도 되겠지?

**Comment by bell-person-ii** [comment]
![1페이지 구현 완료](https://github.com/yongiCorp/Server/assets/76873740/e01f88ff-fb09-4c18-bc98-60666dab0e9b)

1페이지 요구 사항 1차 구현 완료 (메인배너, 서브배너 응답시 각 객체 id 필드 추가 및 Validation 추가 구현 예정)

**Comment by bell-person-ii** [comment]
`{
    "isSuccess": true,
    "code": "COMMON200",
    "message": "성공입니다",
    "data": {
        "mainBanners": {
            "main-banner0": {
                "brand-id": 1,
                "banner-profile": "https://umc.my.test.s3.ap-northeast-2.amazonaws.com/9f98c299-c20e-4708-b34e-a9d75aa8e687.jpg"
            },
            "main-banner1": {
                "brand-id": 6,
                "banner-profile": "https://umc.my.test.s3.ap-northeast-2.amazonaws.com/9c6fc05f-226c-4798-816a-ec276dd6053d.jpg"
            },
            "main-banner2": {
                "brand-id": 5,
                "banner-profile": "https://umc.my.test.s3.ap-northeast-2.amazonaws.com/aa438ef3-a348-4a17-b392-f0a836fbbd99.jpg"
            },
            "main-banner3": {
                "brand-id": 4,
                "banner-profile": "https://umc.my.test.s3.ap-northeast-2.amazonaws.com/8bd9fb21-94b6-49d0-b126-9689e806b953.jpg"
            },
            "main-banner4": {
                "brand-id": 3,
                "banner-profile": "https://umc.my.test.s3.ap-northeast-2.amazonaws.com/189f5e29-54aa-4355-9672-e3ec2d6e3fcd.jpg"
            }
        },
        "subBanners": {
            "sub-banner0": {
                "contents-id": 12,
                "banner-img": "event file"
            },
            "sub-banner1": {
                "contents-id": 11,
                "banner-img": "event file"
            },
            "sub-banner2": {
                "contents-id": 10,
                "banner-img": "event file"
            },
            "sub-banner3": {
                "contents-id": 9,
                "banner-img": "event file"
            },
            "sub-banner4": {
                "contents-id": 8,
                "banner-img": "event file"
            },
            "sub-banner5": {
                "contents-id": 7,
                "banner-img": "event file"
            },
            "sub-banner6": {
                "contents-id": 6,
                "banner-img": "event file"
            },
            "sub-banner7": {
                "contents-id": 5,
                "banner-img": "event file"
            },
            "sub-banner8": {
                "contents-id": 4,
                "banner-img": "event file"
            },
            "sub-banner9": {
                "contents-id": 3,
                "banner-img": "event file3"
            }
        },
        "brandList": {
            "brand0": {
                "brand-id": 1,
                "brand-name": "brandol",
                "brand-image": "https://umc.my.test.s3.ap-northeast-2.amazonaws.com/9f98c299-c20e-4708-b34e-a9d75aa8e687.jpg"
            },
            "brand1": {
                "brand-id": 2,
                "brand-name": "brand-name 1",
                "brand-image": "https://umc.my.test.s3.ap-northeast-2.amazonaws.com/fe6b6f6b-4583-4efe-a9b0-65cea38471ab.jpg"
            },
            "brand2": {
                "brand-id": 3,
                "brand-name": "brand-name 2",
                "brand-image": "https://umc.my.test.s3.ap-northeast-2.amazonaws.com/189f5e29-54aa-4355-9672-e3ec2d6e3fcd.jpg"
            },
            "brand3": {
                "brand-id": 4,
                "brand-name": "brand-name 3",
                "brand-image": "https://umc.my.test.s3.ap-northeast-2.amazonaws.com/8bd9fb21-94b6-49d0-b126-9689e806b953.jpg"
            },
            "brand4": {
                "brand-id": 5,
                "brand-name": "brand-name 4",
                "brand-image": "https://umc.my.test.s3.ap-northeast-2.amazonaws.com/aa438ef3-a348-4a17-b392-f0a836fbbd99.jpg"
            }
        }
    }
}`

**Comment by bell-person-ii** [comment]
{
    "isSuccess": true,
    "code": "COMMON200",
    "message": "성공입니다",
    "data": {
        "mainBanners": {
            "main-banner0": {
                "brand-id": 1,
                "banner-profile": "https://umc.my.test.s3.ap-northeast-2.amazonaws.com/9f98c299-c20e-4708-b34e-a9d75aa8e687.jpg"
            },
            "main-banner1": {
                "brand-id": 6,
                "banner-profile": "https://umc.my.test.s3.ap-northeast-2.amazonaws.com/9c6fc05f-226c-4798-816a-ec276dd6053d.jpg"
            },
            "main-banner2": {
                "brand-id": 5,
                "banner-profile": "https://umc.my.test.s3.ap-northeast-2.amazonaws.com/aa438ef3-a348-4a17-b392-f0a836fbbd99.jpg"
            },
            "main-banner3": {
                "brand-id": 4,
                "banner-profile": "https://umc.my.test.s3.ap-northeast-2.amazonaws.com/8bd9fb21-94b6-49d0-b126-9689e806b953.jpg"
            },
            "main-banner4": {
                "brand-id": 3,
                "banner-profile": "https://umc.my.test.s3.ap-northeast-2.amazonaws.com/189f5e29-54aa-4355-9672-e3ec2d6e3fcd.jpg"
            }
        },
        "subBanners": {
            "sub-banner0": {
                "contents-id": 12,
                "banner-img": "event file"
            },
            "sub-banner1": {
                "contents-id": 11,
                "banner-img": "event file"
            },
            "sub-banner2": {
                "contents-id": 10,
                "banner-img": "event file"
            },
            "sub-banner3": {
                "contents-id": 9,
                "banner-img": "event file"
            },
            "sub-banner4": {
                "contents-id": 8,
                "banner-img": "event file"
            },
            "sub-banner5": {
                "contents-id": 7,
                "banner-img": "event file"
            },
            "sub-banner6": {
                "contents-id": 6,
                "banner-img": "event file"
            },
            "sub-banner7": {
                "contents-id": 5,
                "banner-img": "event file"
            },
            "sub-banner8": {
                "contents-id": 4,
                "banner-img": "event file"
            },
            "sub-banner9": {
                "contents-id": 3,
                "banner-img": "event file3"
            }
        },
        "brandList": {
            "brand0": {
                "brand-id": 1,
                "brand-name": "brandol",
                "brand-image": "https://umc.my.test.s3.ap-northeast-2.amazonaws.com/9f98c299-c20e-4708-b34e-a9d75aa8e687.jpg"
            },
            "brand1": {
                "brand-id": 2,
                "brand-name": "brand-name 1",
                "brand-image": "https://umc.my.test.s3.ap-northeast-2.amazonaws.com/fe6b6f6b-4583-4efe-a9b0-65cea38471ab.jpg"
            },
            "brand2": {
                "brand-id": 3,
                "brand-name": "brand-name 2",
                "brand-image": "https://umc.my.test.s3.ap-northeast-2.amazonaws.com/189f5e29-54aa-4355-9672-e3ec2d6e3fcd.jpg"
            },
            "brand3": {
                "brand-id": 4,
                "brand-name": "brand-name 3",
                "brand-image": "https://umc.my.test.s3.ap-northeast-2.amazonaws.com/8bd9fb21-94b6-49d0-b126-9689e806b953.jpg"
            },
            "brand4": {
                "brand-id": 5,
                "brand-name": "brand-name 4",
                "brand-image": "https://umc.my.test.s3.ap-northeast-2.amazonaws.com/aa438ef3-a348-4a17-b392-f0a836fbbd99.jpg"
            }
        }
    }
}

-> 응답형식 수정완료

**Comment by bell-person-ii** [comment]
유저 메인 페이지 API 구현 완료
